name: validating wf without checkout

on: 
  workflow_dispatch
jobs:
    files:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the repository
              uses: actions/checkout@v5

            - name: display the content of the file.
              run: ls -rth

            - name: print the current working directory
              run: pwd