
name: Testing workflow

on: push

jobs:
    test-job:
        runs-on: ubuntu-latest

        steps:
            - name: Hello display
              run: echo "Hello Github actions...!"

            - name: Display the date
              run: date