name: source code clone
on: 
  workflow_dispatch: 
jobs:
    files:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the repository
              uses: actions/checkout@v5
            - name: display the content of the file
              run: cat devops.txt
            - name: display the date
              run: date
            - name: execute the shell script
              run: ./uptime.sh
